apiVersion: v2
appVersion: auto
dependencies:
  - name: common
    version: '0.3.0'
    repository: https://tvanbolderen.github.io/homelab
deprecated: false
description: Sonarr is a PVR for Usenet and BitTorrent users.
home: https://github.com/Sonarr/Sonarr
icon: https://github.com/Sonarr/Sonarr/blob/develop/Logo/400.png?raw=true
keywords:
  - sonarr
  - torrent
  - usenet
kubeVersion: '>=1.16.0-0'
name: sonarr
sources:
  - https://github.com/Sonarr/Sonarr
  - https://hub.docker.com/r/linuxserver/sonarr
type: application
version: 0.1.4
