{{ if .Values.service.syslog.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}-syslog
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.syslog.type }}
  selector:
    {{- include "common.selectorLabels" . | nindent 4 }}
  ports:
  {{- with .Values.service.syslog }}
    {{- if .ports.syslog.enabled }}
    - name: syslog
      targetPort: syslog
      port: {{ .ports.syslog.port }}
      {{- if or (eq .ports.syslog.protocol "HTTP") (eq .ports.syslog.protocol "HTTPS") }}
      protocol: TCP
      {{- else }}
      protocol: {{ .ports.syslog.protocol | upper }}
      {{- end }}
      {{- if and (eq .type "NodePort") (not (empty .ports.syslog.nodePort)) }}
      nodePort: {{ .ports.syslog.nodePort }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}