apiVersion: v2
appVersion: auto
dependencies:
  - name: common
    version: '0.3.0'
    repository: https://tvanbolderen.github.io/homelab
deprecated: false
description: Bazarr is a companion application to Sonarr and Radarr. It can manage and download subtitles based on your requirements.
home: https://www.bazarr.media
icon: https://www.bazarr.media/assets/img/logo.png
keywords:
  - bazarr
  - radarr
  - sonarr
  - subtitles
  - usenet
  - torrent
kubeVersion: '>=1.16.0-0'
name: bazarr
sources:
  - https://www.bazarr.media
  - https://github.com/morpheus65535/bazarr
  - https://hub.docker.com/r/linuxserver/bazarr
type: application
version: 0.1.2
