apiVersion: str()
kubeVersion: str()
name: str()
version: str(required=True)
appVersion: any(str(), num())
description: str()
type: str(required=False)
deprecated: bool(required=False)
home: str()
icon: str()
engine: str(required=False)
condition: str(required=False)
keywords: list(str(), required=False)
tags: str(required=False)
sources: list(str(), required=False)
dependencies: list(include('dependency'), required=False)
maintainers: list(include('maintainer'), required=False)
annotations: map(str(), str(), required=False)
---
maintainer:
  name: str(required=False)
  email: str(required=False)
  url: str(required=False)
---
dependency:
  name: str()
  repository: str()
  version: str()
  condition: str(required=False)
  tags: list(str(), required=False)
  import-values: any(list(str()), list(include('import-value')), required=False)
  enabled: bool(required=False)
  alias: str(required=False)
---
import-value:
  child: str()
  parent: str()