---
apiVersion: v1
kind: Secret
metadata:
  name: pihole-credentials
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: Opaque
data:
  admin-password: {{ .Values.webInterface.adminPassword | default (randAlphaNum 40) | b64enc | quote }}
