{{ if .Values.service.web.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}-web
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.web.type }}
  selector:
    {{- include "common.selectorLabels" . | nindent 4 }}
  ports:
  {{- with .Values.service.web }}
    {{- if .ports.https.enabled }}
    - name: https
      targetPort: https
      port: {{ .ports.https.port }}
      {{- if or (eq .ports.https.protocol "HTTP") (eq .ports.https.protocol "HTTPS") }}
      protocol: TCP
      {{- else }}
      protocol: {{ .ports.https.protocol | upper }}
      {{- end }}
      {{- if and (eq .type "NodePort") (not (empty .ports.https.nodePort)) }}
      nodePort: {{ .ports.https.nodePort }}
      {{- end }}
    {{- end }}
    {{- if .ports.httpPortal.enabled }}
    - name: http-portal
      targetPort: http-portal
      port: {{ .ports.httpPortal.port }}
      {{- if or (eq .ports.httpPortal.protocol "HTTP") (eq .ports.httpPortal.protocol "HTTPS") }}
      protocol: TCP
      {{- else }}
      protocol: {{ .ports.httpPortal.protocol | upper }}
      {{- end }}
      {{- if and (eq .type "NodePort") (not (empty .ports.httpPortal.nodePort)) }}
      nodePort: {{ .ports.httpPortal.nodePort }}
      {{- end }}
    {{- end }}
    {{- if .ports.httpsPortal.enabled }}
    - name: https-portal
      targetPort: https-portal
      port: {{ .ports.httpsPortal.port }}
      {{- if or (eq .ports.httpsPortal.protocol "HTTP") (eq .ports.httpsPortal.protocol "HTTPS") }}
      protocol: TCP
      {{- else }}
      protocol: {{ .ports.httpsPortal.protocol | upper }}
      {{- end }}
      {{- if and (eq .type "NodePort") (not (empty .ports.httpsPortal.nodePort)) }}
      nodePort: {{ .ports.httpsPortal.nodePort }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}