{{ if .Values.service.stun.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}-stun
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.stun.type }}
  selector:
    {{- include "common.selectorLabels" . | nindent 4 }}
  ports:
  {{- with .Values.service.stun }}
    {{- if .ports.stun.enabled }}
    - name: stun
      targetPort: stun
      port: {{ .ports.stun.port }}
      {{- if or (eq .ports.stun.protocol "HTTP") (eq .ports.stun.protocol "HTTPS") }}
      protocol: TCP
      {{- else }}
      protocol: {{ .ports.stun.protocol | upper }}
      {{- end }}
      {{- if and (eq .type "NodePort") (not (empty .ports.stun.nodePort)) }}
      nodePort: {{ .ports.stun.nodePort }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}