{{- if .Values.ingress.web.enabled }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  entryPoints:
    - {{ .Values.ingress.web.entryPoint }}
  routes:
    - match: {{ .Values.ingress.web.match }}
      kind: Rule
      services:
        - name: {{ include "common.names.fullname" $ }}-web
          port: {{ $.Values.service.web.ports.http.port }}
      middlewares:
        - name: {{ include "common.names.fullname" . }}-addprefix
  tls:
    certResolver: {{ .Values.ingress.web.certResolver }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ include "common.names.fullname" . }}-addprefix
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  addPrefix:
    prefix: /admin
{{- end }}