{{ if .Values.service.dns.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}-dns-tcp
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.dns.type }}
  selector:
    {{- include "common.selectorLabels" . | nindent 4 }}
  ports:
  {{- with .Values.service.dns }}
    {{- if .ports.tcp.enabled }}
    - name: dns-tcp
      targetPort: dns-tcp
      port: {{ .ports.tcp.port }}
      {{- if or (eq .ports.tcp.protocol "HTTP") (eq .ports.tcp.protocol "HTTPS") }}
      protocol: TCP
      {{- else }}
      protocol: {{ .ports.tcp.protocol | upper }}
      {{- end }}
      {{- if and (eq .type "NodePort") (not (empty .ports.tcp.nodePort)) }}
      nodePort: {{ .ports.tcp.nodePort }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}