apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.controller.replicas }}
  strategy:
    type: {{ .Values.controller.strategy }}
    {{- if eq .Values.controller.strategy "RollingUpdate" }}
    rollingUpdate:
      maxSurge: {{ .Values.controller.rollingUpdate.surge }}
      maxUnavailable: {{ .Values.controller.rollingUpdate.unavailable }}
    {{- end }}
  selector:
    matchLabels:
      {{- include "common.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "common.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          ports:
            - name: http
              protocol: TCP
              containerPort: 9091
          env:
            {{- range $name, $value := .Values.env }}
            - name: {{ quote $name }}
              value: {{ quote $value }}
            {{- end }}
            {{- range $envList := .Values.envList }}
            {{- if and $envList.name $envList.value }}
            - name: {{ $envList.name }}
              value: {{ $envList.value | quote }}
            {{- else }}
              {{- fail "Please specify name/value for environment variable" }}
            {{- end }}
            {{- end }}
          volumeMounts:
            - name: transmission-data
              mountPath: {{ .Values.persistence.config.mountPath }}
          {{- if .Values.probes.readiness.enabled }}
          readinessProbe:
            exec:
              command:
                - {{ .Values.probes.readiness.command }}
            initialDelaySeconds: 60
            failureThreshold: 3
            timeoutSeconds: 1
            periodSeconds: 10
          {{- end }}
          {{- if .Values.probes.liveness.enabled }}
          livenessProbe:
            exec:
              command:
                - {{ .Values.probes.liveness.command }}
            initialDelaySeconds: 60
            failureThreshold: 3
            timeoutSeconds: 1
            periodSeconds: 10
          {{- end }}

      volumes:
        - name: transmission-config
          {{- if .Values.persistence.config.enabled }}
          {{- if eq .Values.persistence.config.type "pvc" }}
          persistentVolumeClaim:
            claimName: transmission-config-pvc
          {{- else if eq .Values.persistence.config.type "hostPath" }}
          hostPath:
            path: {{ .Values.persistence.config.hostPath }}
            type: {{ .Values.persistence.config.hostPathType }}
          {{- else }}
            {{- fail (printf "Not a valid persistence.type (%s)" .Values.persistence.config.type) }}
          {{- end }}
          {{- end }}
