---
apiVersion: v1
kind: Secret
metadata:
  name: transmission-credentials
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: Opaque
data:
  openvpn-password: {{ .Values.openvpn.password | default (randAlphaNum 40) | b64enc | quote }}
