{{ if .Values.service.gui.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}-gui
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.gui.type }}
  selector:
    {{- include "common.selectorLabels" . | nindent 4 }}
  ports:
  {{- with .Values.service.gui }}
    {{- if .ports.https.enabled }}
    - name: gui-https
      targetPort: gui-https
      port: {{ .ports.https.port }}
      {{- if or (eq .ports.https.protocol "HTTP") (eq .ports.https.protocol "HTTPS") }}
      protocol: TCP
      {{- else }}
      protocol: {{ .ports.https.protocol | upper }}
      {{- end }}
      {{- if and (eq .type "NodePort") (not (empty .ports.https.nodePort)) }}
      nodePort: {{ .ports.https.nodePort }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}